config/routes.rb
Rails.application.routes.draw do
  mount API::Base, at: "/"
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"

    get "/home", to: "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/signup", to: "users#new"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get ":id/following", to: "following#index", as: "following"
    get ":id/followers", to: "followers#index", as: "followers"
    resources :users
    resources :account_activations, only: %i(edit)
    resources :password_resets, only: %i(new create edit update)
    resources :microposts, only: %i(create destroy)
    resources :relationships, only: %i(create destroy)
 end
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t "layouts.application.form" %>
      <%= t "users.signup.count", count: object.errors.size %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= paginate @feed_items,
    params: {controller: :static_pages, action: :home},
    theme: Settings.theme.name_bootstrap %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for @micropost do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: t("microposts.new.content") %>
  </div>
  <%= f.submit t("microposts.new.post"), class: "btn btn-primary" %>
  <span class="image">
    <%= f.file_field :image, accept: Settings.accept.image %>
  </span>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
   <%= link_to following_path @user do %>
    <strong id="following" class="stat">
      <strong id="followers" class="stat">
      <%= t "users.following.count" , count: @user.following.size %>
    </strong>
    </strong>
    <%= t "users.controllers.following" %>
  <% end %>
  <%= link_to followers_path @user do %>
    <strong id="followers" class="stat">
      <%= t "users.followers.count" , count: @user.followers.size %>
    </strong>
    <%= t "users.controllers.follower" %>
  <% end %>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: Settings.number.size), current_user %>
<h1><%= current_user.name %></h1>
<span>
  <%= link_to t("microposts.new.view"), current_user %>
</span>
<span>
  <%= t "microposts.new.count", count: current_user.microposts.size %>
</span>