config/routes.rb
Rails.application.routes.draw do
  mount API::Base, at: "/"
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"

    get "/home", to: "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/signup", to: "users#new"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get ":id/following", to: "following#index", as: "following"
    get ":id/followers", to: "followers#index", as: "followers"
    resources :users
    resources :account_activations, only: %i(edit)
    resources :password_resets, only: %i(new create edit update)
    resources :microposts, only: %i(create destroy)
    resources :relationships, only: %i(create destroy)
 end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to t("static_pages.about.title"), Settings.link.about %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t("static_pages.about.title"), about_path %></li>
      <li><%= link_to t("static_pages.contact.title"), contact_path %></li>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("layouts.application.title"), Settings.link.home , id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("static_pages.home.title"), home_path %></li>
        <li><%= link_to t("static_pages.help.title"), help_path %></li>
        <li><%= link_to t("static_pages.about.title"), about_path %></li>
        <% if logged_in? %>
          <li><%= link_to t("layouts.application.users"), users_path %></li>
          <li class="dropdown">
            <%= link_to "#", class: "dropdown-toggle",
              "data-toggle": "dropdown" do %>
              <%= t "layouts.application.account" %>
              <b class="caret"></b>
            <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to t("layouts.application.profile"), current_user %></li>
              <li><%= link_to t("layouts.application.setting"), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t("layouts.application.logout"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("layouts.application.login"), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
<%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
<%= link_to t(".english"), locale: :en %>
<%= link_to t(".vietnam"), locale: :vi %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield :title) %></title>
    <%= render "layouts/rails_default" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>">
          <%= message %>
        </div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>